export enum BusinessEventType {
  NEWS_INSIGHT_SUBSCRIBER_CREATED = 'NEWS_INSIGHT_SUBSCRIBER_CREATED',
  BUSINESS_ENQUIRY_CREATED = 'BUSINESS_ENQUIRY_CREATED',
  BUSINESS_LEAD_CREATED = 'BUSINESS_LEAD_CREATED',
  JOB_APPLICANT_CREATED = 'JOB_APPLICANT_CREATED',
  JOB_APPLICATION_CREATED = 'JOB_APPLICATION_CREATED',
}
