name: Deploy Backend to EC2

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Update package lists
        run: sudo apt-get update

      # - name: Install AWS CLI
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y awscli

      # - name: Configure AWS Credentials
      #   run: |
      #     aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
      #     aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
      #     aws configure set region us-east-1

      - name: SSH to EC2 Instance and Deploy Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo yum update
            # aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
            # aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
            # aws configure set region us-east-1
            cd keyvar-backend/
            git remote add keyvar https://github.com/Perebonilado/keyvar.git
            git pull keyvar main
            sudo npm install  # Install dependencies
            sudo nest build  # Build your backend if needed
            pm2 restart keyvar-prod --update-env  # Restart your backend server using PM2 or other process manager
            pm2 logs
